var glob = require("glob")
var fs = require('fs');

var OUTPUT_FILENAME = 'vue_components.js';


function getName(path) {
	splited_path = path.split('/');
	var n = splited_path[splited_path.length - 1];
	var name = n.split('.')[0];
	return name;
}


// options is optional 
glob("src/components/**/*.vue", function(er, files) {
	var docs = [];

	files.forEach(function(file) {
		var new_file = {};

		new_file.name = getName(file);
		new_file.path = file;

		var find = 'src/';
		var re = new RegExp(find, 'g');

		new_file.path = new_file.path.replace(re, './');
		docs.push(new_file);
	});

	var string_file = "//DO NOT UPDATE THIS FILE \n // This file is AUTOGENERATED in vue-app/generateComponentsPaths.js\n\nexport default" + JSON.stringify(docs);
	fs.writeFile("./src/" + OUTPUT_FILENAME, string_file, function(err) {
		if (err) {
			console.log("there was an error saving files");
		} else {
			console.log("Compiling components...")
			console.log(OUTPUT_FILENAME + " has been generated")
		}
	});
})