//DO NOT UPDATE THIS FILE 
 // This file is AUTOGENERATED in vue-app/generateComponentsPaths.js

export default[{"name":"MaterialCalendar","path":"./components/material-calendar/MaterialCalendar.vue"},{"name":"users","path":"./components/users/users.vue"}]